import { deflateSync } from "node:zlib";
import { expect, test } from "@playwright/test";
import { APP_VIEWPORT, addNode, connect, fitAll, moveNode, openApp, selectNode } from "./app.ts";

/**
 * ⚑ T1223 — A PICKED STILL REACHES THE GLASS, AND IS STILL THERE A SECOND LATER.
 *
 * `movieFileIn` claimed *"Plays a video or still image file"* from T493 while
 * `use-media-sources` called `document.createElement("video")` and nothing else. A picked
 * PNG produced black with no diagnostic. Everything else T1223 added can be asserted
 * headlessly — the classifier, the one-frame source, the dimmed transport — but ONE link
 * cannot: `queue.copyExternalImageToTexture` does not exist in `vgpu/node`, so an
 * `image`-payload frame is uploaded by NO Dawn suite in this project. This lane is the only
 * place the decoded bitmap actually becomes pixels (§V895, §V628), which is why the claim
 * lives here and not next to the code.
 *
 * ## The two halves of the owner's sentence, as one assertion
 *
 * *"Images … played back as a continuous video stream, so it becomes transparent for
 * anyone who consumes it."* That is (a) the picture is there, and (b) it is STILL there,
 * unchanged, after the frame loop has run hundreds of times — which is also §V136's
 * upload-once claim, because a still's `frameId` never advances and an unchanged id means
 * the backend uploads nothing. So the second read is not a repeat of the first: between
 * them the texture is never re-uploaded, and if the still path leaked its bitmap, cleared
 * the texture, or advanced its id into a re-upload of a closed bitmap, the second read is
 * where it shows.
 *
 * ## Why the bytes are EXACT (§V147), with no tolerance band
 *
 * The fixture is generated here rather than committed, so its values are stated in code:
 * two bands of PURE RED and PURE BLUE, both fully opaque. 0 and 255 are fixed points of
 * every transform between the file and the glass — the PNG decode, the `-srgb` texture's
 * hardware decode to linear (§V56), the Output pass's encode back, 8-bit quantisation,
 * premultiplication at alpha 1, and any display profile a headed screenshot picks up. The
 * probes sit at the middle of each band, tens of pixels from the seam, so the blit's
 * resampling is averaging a constant and returns it exactly.
 *
 * ORIENTATION IS PART OF THE CLAIM, deliberately. Unlike `presentation-pixels`' checker —
 * generated by a pass, so a uv flip is applied on write and on read and cancels — a still
 * is COPIED into the texture by `copyExternalImageToTexture` and only sampled once. Nothing
 * cancels. A picture served upside down is a defect a colour-only assertion would pass, so
 * the red band is asserted at the TOP, where the file has it.
 */

test.use({ viewport: APP_VIEWPORT });

/** Pure red over pure blue: two bands, both alpha 255, no value that is not 0 or 255. */
const IMAGE_WIDTH = 128;
const IMAGE_HEIGHT = 128;

function crc32(bytes: Buffer): number {
  let crc = ~0;
  for (const byte of bytes) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit += 1) crc = (crc >>> 1) ^ (0xed_b8_83_20 & -(crc & 1));
  }
  return ~crc >>> 0;
}

function chunk(type: string, body: Buffer): Buffer {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(body.length);
  const tagged = Buffer.concat([Buffer.from(type, "latin1"), body]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(tagged));
  return Buffer.concat([length, tagged, crc]);
}

/**
 * A minimal RGBA PNG, written here so the fixture's exact bytes are readable in the test
 * that asserts them — a committed binary would make the expected values an article of
 * faith. Filter byte 0 (None) on every row, so the pixel bytes are literal.
 */
function bandedPng(): Buffer {
  const raw = Buffer.alloc((IMAGE_WIDTH * 4 + 1) * IMAGE_HEIGHT);
  let cursor = 0;
  for (let y = 0; y < IMAGE_HEIGHT; y += 1) {
    raw[cursor] = 0;
    cursor += 1;
    const top = y < IMAGE_HEIGHT / 2;
    for (let x = 0; x < IMAGE_WIDTH; x += 1) {
      raw[cursor] = top ? 255 : 0;
      raw[cursor + 1] = 0;
      raw[cursor + 2] = top ? 0 : 255;
      raw[cursor + 3] = 255;
      cursor += 4;
    }
  }
  const header = Buffer.alloc(13);
  header.writeUInt32BE(IMAGE_WIDTH, 0);
  header.writeUInt32BE(IMAGE_HEIGHT, 4);
  header[8] = 8; // bit depth
  header[9] = 6; // colour type: RGBA
  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk("IHDR", header),
    chunk("IDAT", deflateSync(raw)),
    chunk("IEND", Buffer.alloc(0)),
  ]);
}

test("a picked PNG reaches the glass, and the same bytes are there a second later", async ({
  page,
}) => {
  await openApp(page);

  const movie = await addNode(page, "input", "Movie File In");
  const output = await addNode(page, "output", "Output");
  await fitAll(page);
  await moveNode(page, output, 260, 240);
  // Same bounded retry as `presentation-pixels`: under a live GPU React Flow occasionally
  // drops a release its own `connectingto` class had blessed a frame earlier. The claim is
  // downstream of however many attempts the wire took.
  for (let attempt = 0; ; attempt += 1) {
    try {
      await connect(page, { nodeId: movie, portId: "out" }, { nodeId: output, portId: "input" });
      await expect(page.locator(".react-flow__edge")).toHaveCount(1, { timeout: 2000 });
      break;
    } catch (error) {
      if (attempt >= 2) throw error;
    }
  }

  // THE OWNER'S GESTURE, through the product's own control: the inspector's file input,
  // whose `accept` this task widened. `setInputFiles` drives the real `change` handler, so
  // the value under test is the object URL the picker builds — fragment and all, which is
  // the only place a `blob:` URL carries the extension the loader classifies on.
  await selectNode(page, movie);
  const picker = page.locator('input[type="file"]');
  await expect(picker).toHaveCount(1);
  await picker.setInputFiles({
    name: "loom-bands.png",
    mimeType: "image/png",
    buffer: bandedPng(),
  });

  await expect(page.getByTestId("viewer-canvas")).toBeVisible();
  await expect
    .poll(
      () =>
        page.evaluate(async () => {
          const probe = (
            window as unknown as {
              loomViewerProbe?: () => Promise<{
                presentation: { presentedFrames: number; sourceBound: boolean } | null;
              }>;
            }
          ).loomViewerProbe;
          const presentation = (await probe?.())?.presentation ?? null;
          return presentation !== null && presentation.sourceBound && presentation.presentedFrames > 0;
        }),
      { message: "the runtime never presented a frame into the viewer canvas" },
    )
    .toBe(true);

  /** The compositor's own pixels at the middle of each band — see the docblock. */
  const readBands = async (): Promise<readonly number[] | null> => {
    const shot = await page.getByTestId("viewer-canvas").screenshot();
    return page.evaluate(async (base64) => {
      const image = new Image();
      image.src = `data:image/png;base64,${base64}`;
      await image.decode();
      if (image.naturalWidth < 16 || image.naturalHeight < 16) return null;
      const copy = document.createElement("canvas");
      copy.width = image.naturalWidth;
      copy.height = image.naturalHeight;
      const ctx = copy.getContext("2d", { willReadFrequently: true });
      if (ctx === null) return null;
      ctx.drawImage(image, 0, 0);
      const data = ctx.getImageData(0, 0, copy.width, copy.height).data;
      const at = (fx: number, fy: number): number[] => {
        const x = Math.round(fx * copy.width);
        const y = Math.round(fy * copy.height);
        const base = (y * copy.width + x) * 4;
        return [data[base] ?? -1, data[base + 1] ?? -1, data[base + 2] ?? -1, data[base + 3] ?? -1];
      };
      return [...at(0.5, 0.25), ...at(0.5, 0.75)];
    }, shot.toString("base64"));
  };

  const expected = [255, 0, 0, 255, 0, 0, 255, 255];
  await expect
    .poll(async () => (await readBands())?.join(",") ?? "unreadable", {
      message:
        "the canvas never showed the picked still — before T1223 this is BLACK with no " +
        "diagnostic, because the loader only ever built a <video>",
      timeout: 20_000,
    })
    .toBe(expected.join(","));

  /*
   * ⚑ THE SECOND HALF, and the one that is about a STILL rather than about any picture:
   * hundreds of frames later, with nothing re-uploaded (the `frameId` never advanced), the
   * same bytes are on the glass. A stream that held its last frame and a still are the same
   * thing to everything downstream — which is exactly the transparency the owner asked for.
   */
  const framesLater = await page.evaluate(
    () =>
      new Promise<number>((resolve) => {
        let frames = 0;
        const step = () => {
          frames += 1;
          if (frames >= 120) resolve(frames);
          else requestAnimationFrame(step);
        };
        requestAnimationFrame(step);
      }),
  );
  expect(framesLater).toBe(120);
  expect(await readBands()).toEqual(expected);
});
