/**
 * The velocity kernel carried by example E12 (T362).
 *
 * This is the `source` parameter of that example's CustomWGSL node. It lives here as a
 * TypeScript constant for the same reason E2's Gray-Scott kernel does: the example is
 * REGENERATED by `src/examples/build-examples.ts` rather than hand-edited as escaped
 * JSON, and `sync.test.ts` fails if the shipped file and this source drift apart.
 *
 * WHAT IT IS. Half of a fluid: the velocity field that carries E12's dye. The other half
 * is not in here at all — it is a Displace node, because backward semi-Lagrangian
 * advection IS what Displace does, and writing a second copy of it in WGSL would put the
 * example's central operation somewhere the graph cannot show it.
 *
 * THE UNIT IS ONE STEP, NOT ONE SECOND, and that is a decision rather than an oversight.
 * `.rg` holds a displacement per FRAME, so the field advects itself with `uv - here` and
 * the dye advects with a Displace whose weight is exactly -1. Storing metres-per-second
 * instead would force the frame duration into Displace's `weight`, which is a compile-time
 * uniform (§V21) — a fixed 1/60 baked into a parameter, silently wrong at any other rate.
 * E2 made the same choice for the same reason: one frame advanced is one simulation step.
 *
 * THE POINTER IS THE STIRRING FORCE (§V182, §V236). `frameU.pointer.xy` is the shared
 * frame block's pointer — the SAME 0..1, v-down coordinate the viewer publishes and the
 * Mouse node reads on the CPU side, never a second listener. The force is TANGENTIAL: a
 * vortex around the cursor rather than a push away from it, because a push needs the
 * pointer's VELOCITY and a shader has no previous frame to difference against. A vortex
 * needs only where the cursor is, so it is deterministic under replay (§V44/§V45) and it
 * is what "stirring" actually looks like.
 *
 * CONTRACT (§I "custom WGSL node contract v1"). Four bindings, matched by NAME, in the
 * layout the shipped default source uses: `inputSampler` 0, `inputTexture` 1, `frameU` 2,
 * `params` 3. Unlike E2's kernel this one DECLARES both uniform blocks, so the node's
 * `compile()` binds both (it scans the source for the declaration — declared, then bound,
 * never bound blindly). `params.amount` is the stir strength, live on a uniform write.
 *
 * NO AMBIENT GLOBALS (§V280): everything here is WGSL and shader constants. The grid
 * spacing comes from `textureDimensions`, as E2's does.
 */
export const FLUID_VELOCITY_WGSL = `struct SharedFrame {
  time: f32,
  deltaTime: f32,
  frameIndex: f32,
  randomSeed: f32,
  wallTime: f32,
  wallDelta: f32,
  resolution: vec2f,
  pointer: vec4f,
};
struct Params {
  amount: f32,
};

@group(0) @binding(0) var inputSampler: sampler;
@group(0) @binding(1) var inputTexture: texture_2d<f32>;
// Filled by the runtime from FrameEvaluationInput every frame. There is no other clock
// here, and no other pointer (§V44, §V182).
@group(0) @binding(2) var<uniform> frameU: SharedFrame;
@group(0) @binding(3) var<uniform> params: Params;

/** How much of the four-neighbour mean each step mixes in. This is the viscosity. */
const VISCOSITY: f32 = 0.16;
/** Per-step drain. S / (1 - D) is the CEILING it implies; viscosity and the walls take
    more, so the measured speed below is a third of that arithmetic (§V206: the number
    here is a measurement, not a derivation). */
const DAMPING: f32 = 0.994;
/** Gaussian falloff of the stirring vortex, in uv units. */
const STIR_RADIUS: f32 = 0.19;
/** Measured on Dawn: the field settles near 0.0033 uv/step — about two pixels a frame at 640. */
const STIR_STRENGTH: f32 = 0.00008;
/** No-slip band: velocity is faded to zero inside this margin, so the box holds its fluid. */
const WALL: f32 = 0.05;

@fragment
fn fs(@location(0) uv: vec2f) -> @location(0) vec4f {
  let texel = 1.0 / vec2f(textureDimensions(inputTexture));

  // SELF-ADVECTION, backward: the velocity here now is the velocity that was one step
  // upstream. The same operation the dye gets from Displace, in the same unit.
  let here = textureSample(inputTexture, inputSampler, uv).xy;
  var v = textureSample(inputTexture, inputSampler, uv - here).xy;

  // VISCOSITY: one relaxation toward the four-neighbour mean. Two fluids differ mostly in
  // how fast this term erases the small structure the advection keeps making.
  let west = textureSample(inputTexture, inputSampler, uv - vec2f(texel.x, 0.0)).xy;
  let east = textureSample(inputTexture, inputSampler, uv + vec2f(texel.x, 0.0)).xy;
  let south = textureSample(inputTexture, inputSampler, uv - vec2f(0.0, texel.y)).xy;
  let north = textureSample(inputTexture, inputSampler, uv + vec2f(0.0, texel.y)).xy;
  v = mix(v, (west + east + south + north) * 0.25, VISCOSITY);

  // THE MOUSE. A vortex centred on the pointer: the tangent of the radius, so pointing at
  // the fluid spins it rather than blowing it away. v runs DOWN in both halves (§V236), so
  // the swirl is under the cursor and not mirrored across the frame.
  let toward = uv - frameU.pointer.xy;
  let radial = length(toward);
  let falloff = exp(-(radial * radial) / (STIR_RADIUS * STIR_RADIUS));
  let tangent = vec2f(-toward.y, toward.x) / max(radial, 1e-4);
  v = v + (tangent * (falloff * STIR_STRENGTH * params.amount));

  v = v * DAMPING;

  // Walls. Without this the clamped sampler recirculates the border velocity for ever and
  // the fluid climbs into a corner and stays there.
  let edge = min(min(uv.x, 1.0 - uv.x), min(uv.y, 1.0 - uv.y));
  v = v * smoothstep(0.0, WALL, edge);

  // b is unused; a is 1 so the field is never mistaken for an empty target.
  return vec4f(v, 0.0, 1.0);
}`;
