import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { EXAMPLES_DIR, STARTER_COMPONENTS_DIR } from "./catalogue.ts";
import { buildStarterComponentFiles } from "./component-files.ts";
import { buildStarterComponents } from "./starter-components.ts";
import { buildExampleFiles } from "./example-files.ts";
import { matchesOnlyFlag } from "./only-flag.ts";

/**
 * Regenerates `examples/*.loom.json` and `examples/components/*.loom.json` (T153-T156, T190).
 *
 *   node --import ./src/tooling/alias-hooks.ts src/examples/build-examples.ts
 *
 * Running this is the ONLY way an example changes: edit `documents.ts`, re-run, commit the
 * regenerated file. `sync.test.ts` fails the build if a shipped file and its source have
 * drifted, so a hand-edit of the JSON is caught rather than quietly kept.
 *
 * Writing happens on import — this module is a script and nothing else imports it.
 */

/**
 * T698: `--only <name>` writes just the matching files. Five workers share this tree
 * through windowed files, and a bare regen sweeps up every other worker's in-flight
 * document changes — regenerate only what your change touched.
 *
 * T1267/B197: an E-number argument (`--only E2`) names ONE example and is matched exactly;
 * substring matching is kept for every other shape (`--only E2-Reaction`, `--only Reaction`).
 * See `only-flag.ts`.
 *
 * T1221: `--only` selects STARTER COMPONENTS by the same predicate against the same file
 * names it writes (`--only Bloom` -> `examples/components/Bloom.loom.json`). It used to
 * skip the component half outright, which left the unscoped run — the one the contention
 * rule forbids — as the only shipped route to regenerate a component. One flag, one rule,
 * both halves: a session that has to learn a second addressing scheme will reach for the
 * unscoped run instead. An argument that matches an example AND a component regenerates
 * both, deliberately; the plan lines below are what make that blast radius visible before
 * a byte moves.
 */
const onlyAt = process.argv.indexOf("--only");
const only = onlyAt >= 0 ? process.argv[onlyAt + 1] : undefined;
if (onlyAt >= 0 && only === undefined) throw new Error("--only needs a name substring");

/**
 * T1221: `--out <dir>` writes the regenerated bytes to `<dir>/` and `<dir>/components/`
 * instead of the shipped locations — preview a regen without touching the working tree,
 * and the only way `only-flag.test.ts` can assert WHICH FILES a run writes without
 * overwriting shipped ones on every test run. Absent, the shipped locations are used, so
 * every existing invocation is byte-for-byte the run it was.
 */
const outAt = process.argv.indexOf("--out");
const out = outAt >= 0 ? process.argv[outAt + 1] : undefined;
if (outAt >= 0 && out === undefined) throw new Error("--out needs a directory");
const examplesDir = out ?? EXAMPLES_DIR;
const componentsDir = out === undefined ? STARTER_COMPONENTS_DIR : join(out, "components");

/* T956: examples that INSTANCE a library component embed its definition, so the starter
   set is authored first even under --only — the definitions are deterministic and cheap. */
const starterDefinitions = (await buildStarterComponents()).map((built) => built.definition);

const matches = (fileName: string): boolean =>
  only === undefined || matchesOnlyFlag(fileName, only);

const selectedExamples = buildExampleFiles(starterDefinitions).filter((file) =>
  matches(file.fileName),
);
// Components are authored by running the real authoring commands, so this half is async.
const selectedComponents = (await buildStarterComponentFiles()).filter((file) =>
  matches(file.fileName),
);
if (only !== undefined && selectedExamples.length === 0 && selectedComponents.length === 0) {
  throw new Error(`--only ${only} matched no example or component`);
}

/* T1267: say what is about to be OVERWRITTEN before a byte moves, scoped run or not — the
   sweep in B197 was invisible until `git status` showed seven foreign files rewritten.
   T1221: both halves, because both halves are now scopable. */
const planLine = (kind: string, files: readonly { readonly fileName: string }[]): string =>
  `writing ${files.length} ${kind}${files.length === 1 ? "" : "s"}` +
  (files.length === 0 ? "" : `: ${files.map((file) => file.fileName).join(", ")}`);
console.log(planLine("example", selectedExamples));
console.log(planLine("component", selectedComponents));

if (out !== undefined) {
  mkdirSync(examplesDir, { recursive: true });
  mkdirSync(componentsDir, { recursive: true });
}

for (const file of selectedExamples) {
  const path = join(examplesDir, file.fileName);
  writeFileSync(path, file.text, "utf8");
  console.log(`wrote ${path}`);
}

for (const file of selectedComponents) {
  const path = join(componentsDir, file.fileName);
  writeFileSync(path, file.text, "utf8");
  console.log(`wrote ${path}`);
}
