import { describe, expect, it } from "vitest";
import { compileGraph } from "../compiler/index.ts";
import { createComponentSystem } from "../domain/components/registry.ts";
import { graphComponentDefinitionSchema } from "../domain/components/schemas.ts";
import { readComponentInstance } from "../domain/components/instance.ts";
import { defaultValueOf } from "../domain/components/parameter-defaults.ts";
import {
  PROJECT_FILE_EXTENSION,
  loadProject,
  serializeProjectDocument,
} from "../domain/project/index.ts";
import type { GraphComponentDefinition } from "../domain/types/components.ts";
import type { ParameterSlot, ParameterValue } from "../domain/types/parameters.ts";
import { createNodeRegistry } from "../nodes/registry/registry.ts";
import { allNodeDefinitions } from "../nodes/definitions/index.ts";
import { listStarterComponentFiles } from "./catalogue.ts";
import { buildStarterComponentFiles } from "./component-files.ts";
import { STARTER_COMPONENT_SPECS } from "./starter-components.ts";
import { TIER_B_CAPABILITIES, messagesOf } from "./runner.ts";

/**
 * The starter component set (T190, §V94, §V89).
 *
 * `sync.test.ts` keeps the shipped EXAMPLES honest: they are generated by the real save
 * path and this suite fails if a shipped file drifted from its source. §V94 asks for the
 * same guarantee one layer deeper — a shipped component must be the same
 * `GraphComponentDefinition` a user's own save produces, not a privileged format — so the
 * starter set is generated by running the real AUTHORING commands and then the real save
 * path, and the same byte comparison applies.
 *
 * Byte-identity alone would still let the set ship components that cannot render, so
 * §V89's gate applies too: every file loads through the loader a user's file goes through,
 * installs its library, compiles clean and reaches an Output.
 *
 * Fix a failure by editing `starter-components.ts` and re-running:
 *
 *   node --import ./src/mcp/alias-hooks.ts src/examples/build-examples.ts
 */

const shipped = new Map(listStarterComponentFiles().map((file) => [file.fileName, file.text]));

/** Load + compile with a component-aware registry, which `runExample` deliberately lacks. */
function open(text: string) {
  const { components, nodes } = createComponentSystem(createNodeRegistry(allNodeDefinitions).view());
  const loaded = loadProject(text, { nodes, components });
  if (!loaded.ok) throw new Error(`did not load: ${loaded.reason}`);
  const plan = compileGraph({
    graph: loaded.document.graph,
    settings: loaded.document.settings,
    registry: nodes,
    capabilities: TIER_B_CAPABILITIES,
    components: components.view(),
  });
  return { loaded, plan, components };
}

/** The library the file carries, straight off the JSON — what the loader was handed. */
function libraryOf(text: string): readonly GraphComponentDefinition[] {
  const parsed = JSON.parse(text) as { componentLibrary?: { components?: unknown } };
  return (parsed.componentLibrary?.components ?? []) as readonly GraphComponentDefinition[];
}

describe("the shipped starter components are what the save path writes (§V94)", () => {
  it("ships exactly the files the builder writes", async () => {
    const generated = await buildStarterComponentFiles();
    expect([...shipped.keys()].sort()).toEqual(generated.map((file) => file.fileName).sort());
  });

  it("is byte-identical to a fresh authoring pass, file by file", async () => {
    const generated = await buildStarterComponentFiles();
    for (const file of generated) {
      expect(shipped.get(file.fileName), file.fileName).toBe(file.text);
    }
  });

  it("names the seven the spec asks for", () => {
    expect(STARTER_COMPONENT_SPECS.map((spec) => spec.name).sort()).toEqual([
      "AudioLevel",
      "Bloom",
      "DepthPoints",
      "DisplacementStack",
      "FeedbackEcho",
      "Kaleidoscope",
      "MediaGrade",
    ]);
  });

  it.each([...shipped.keys()])("%s survives a load/save round trip", (fileName) => {
    const text = shipped.get(fileName) as string;
    const { loaded } = open(text);
    // The library rides at the document root, so a document serialized on its own is NOT
    // the file. What must hold is that the loader changed nothing it lifted out.
    expect(loaded.changed).toBe(false);
    expect(serializeProjectDocument(loaded.document).length).toBeGreaterThan(0);
    expect(fileName.endsWith(PROJECT_FILE_EXTENSION)).toBe(true);
  });

  /**
   * §V94's actual claim. A privileged format is one the user's own save could not produce,
   * and the cheapest way for that to happen is a field the authoring path never writes. So
   * the shipped definition is re-validated through the SAME zod schema a user's file is
   * validated by, and every key is one the schema names.
   */
  it.each([...shipped.keys()])("%s carries a definition the file schema accepts", (fileName) => {
    const library = libraryOf(shipped.get(fileName) as string);
    expect(library).toHaveLength(1);
    const parsed = graphComponentDefinitionSchema.safeParse(library[0]);
    expect(parsed.success ? [] : parsed.error.issues.map((issue) => issue.message)).toEqual([]);
  });
});

describe("every starter component renders (§V89)", () => {
  it.each([...shipped.keys()])("%s loads with nothing to report", (fileName) => {
    const { loaded } = open(shipped.get(fileName) as string);
    expect(messagesOf(loaded.diagnostics)).toEqual([]);
    // A placeholder means the file names a node this build does not have (§V10) — for a
    // shipped file that is never "kept for forward compatibility", it is a broken file.
    expect(loaded.placeholders).toEqual([]);
  });

  it.each([...shipped.keys()])("%s compiles clean and reaches an Output", (fileName) => {
    const { plan } = open(shipped.get(fileName) as string);
    expect(messagesOf(plan.diagnostics)).toEqual([]);
    expect(plan.passes.length).toBeGreaterThan(0);
    // NON-VACUITY: a plan with no work would satisfy "no diagnostics" perfectly.
    expect(plan.pruned).toEqual([]);
  });

  it.each([...shipped.keys()])("%s instantiates its own component (§V79)", (fileName) => {
    const text = shipped.get(fileName) as string;
    const { loaded } = open(text);
    const definition = libraryOf(text)[0] as GraphComponentDefinition;

    const instances = Object.values(loaded.document.graph.nodes)
      .map((node) => readComponentInstance(node))
      .filter((state) => state !== null);
    expect(instances).toHaveLength(1);
    // Pinned to the version the file ships, not to "latest" (§V84).
    expect(instances[0]?.componentId).toBe(definition.componentId);
    expect(instances[0]?.version).toBe(definition.version);
  });
});

/**
 * A published knob writes its resolved value onto every internal target on each flatten
 * (§V80). So a published DEFAULT that disagrees with the value the internal node was
 * authored with does not sit there harmlessly — it re-grades the component the moment
 * anyone instantiates it, and the shipped demo would not match the shipped component.
 *
 * This is the one property of the set that no schema, byte comparison or compile can
 * catch, because every one of those is equally happy with a wrong number.
 */
/**
 * T518 — WHAT A PUBLISHED DEFAULT IS ACTUALLY BEING COMPARED AGAINST, once a host node's
 * parameter is a SLOT rather than a bare number.
 *
 * E5's fold and spin angles and E6's field rotation are `expression` slots now, because an
 * example has to move (T402). A slot is not a number, so a naive comparison against the
 * published default can never match and the check would have to be deleted — which is the
 * wrong repair, because the property it guards is real.
 *
 * The right comparison is the slot's STATIC binding, and §V108 says why: `retained` is what
 * any host WITHOUT that channel attached resolves to, and a component instance in someone
 * else's project is exactly such a host. So the retained value IS the value a fresh
 * instance gets, and matching the published default to it is precisely the "the shipped
 * demo matches the shipped component" property.
 *
 * A slot with no static binding still FAILS, loudly: there is no value for a component
 * instance to fall back to, and silently publishing a default over it would be inventing
 * one.
 */
function retainedValueOf(
  authored: ParameterValue | ParameterSlot | undefined,
  where: string,
): ParameterValue | undefined {
  if (authored === null || typeof authored !== "object" || Array.isArray(authored)) {
    return authored as ParameterValue | undefined;
  }
  if (!("mode" in authored) || !("bindings" in authored)) return authored as ParameterValue;
  const slot = authored as ParameterSlot;
  const staticBinding = slot.bindings.static;
  if (staticBinding === undefined || staticBinding.kind !== "static") {
    throw new Error(
      `${where} is a ${slot.mode} slot with no static binding, so a component instance ` +
        `has nothing to fall back to (§V108). Give it a retained value, or do not publish it.`,
    );
  }
  return staticBinding.value;
}

describe("a published default matches the internal value it drives (§V80)", () => {
  it.each(STARTER_COMPONENT_SPECS.map((spec) => spec.name))("%s", (name) => {
    const spec = STARTER_COMPONENT_SPECS.find((entry) => entry.name === name);
    if (spec === undefined) throw new Error(`no spec named ${name}`);

    const mismatches: string[] = [];
    for (const published of spec.publish) {
      for (const target of published.targets) {
        const node = spec.host.graph.nodes[target.nodeId];
        const authored = retainedValueOf(
          node?.parameters[target.key] as ParameterValue | ParameterSlot | undefined,
          `${spec.name}.${target.nodeId}.${target.key}`,
        );
        // Through `defaultValueOf`, which is what a fresh instance actually gets.
        const fallback = defaultValueOf(published.definition);
        if (JSON.stringify(authored) !== JSON.stringify(fallback)) {
          mismatches.push(
            `${published.key} defaults to ${JSON.stringify(fallback)} but ${target.nodeId}.${target.key} is ${JSON.stringify(authored)}`,
          );
        }
      }
    }
    expect(mismatches).toEqual([]);
  });
});
