import { describe, expect, it } from "vitest";

import { liveClock } from "./live-clock.ts";
import { offlineTransport } from "../../runtime/execution/offline-transport.ts";
import { scopeFromFrame, evaluateExpression } from "../expressions/evaluate.ts";
import { resolveParameters } from "../parameters/resolve.ts";
import { dispatchFrameUniforms, sharedUniformsFromFrame, SHARED_UNIFORMS_WGSL } from "../../runtime/backend/shared-uniforms.ts";
import { generateKernelModule, generateSpawnHookModule } from "../../points/codegen.ts";
import { allNodeDefinitions } from "../../nodes/definitions/index.ts";
import {
  MEDIA_TRANSPORT_KEYS,
  MEDIA_TRANSPORT_PARAMETERS,
  createMediaClock,
  hasMediaTransport,
  mediaPlayhead,
  type MediaTransportValues,
} from "../media/transport.ts";
import { absFrameIndexOf, absTimeSecondsOf, type FrameEvaluationInput } from "../types/frame.ts";
import type { NodeDefinition } from "../types/node-definition.ts";
import type { GraphNode } from "../types/graph.ts";
import type { PointAttributeSchema } from "../../points/attributes.ts";

/**
 * ═══════════════════════════════════════════════════════════════════════════════════
 * T489 — THE PROPERTY: **NOTHING RESETS AT THE LOOP.**
 * ═══════════════════════════════════════════════════════════════════════════════════
 *
 * ## Why this file is shaped like this
 *
 * The owner asked for one thing, once: "abstime should be something that keeps growing and
 * does not get set, so we have one thing that can be referenced — analogous to abstime in
 * TouchDesigner. Right now time and frame both reset at the end."
 *
 * They then hit it FOUR times. Expressions got the absolute clock (T461). Then texture
 * shaders were found without it (T468). Then point kernels were found without it (B97, in
 * the owner's own project). Then the LFO was found reading the lapping clock (B98). Every
 * round shipped a SITE and checked it off; nobody ever asserted the PROPERTY. That is
 * §V437, and this file is the answer to it.
 *
 * So the unit under test is NOT a feature. It is a claim about every surface at once:
 *
 *   **No clock-reading surface may see a value DECREASE across a timeline loop.**
 *
 * ## What "surface" means, and why the list is here rather than implied
 *
 * A surface is anywhere a clock reaches user-authored content or a user-visible value.
 * Enumerated (T489's deliverable), with how each one gets the absolute pair:
 *
 *   1. THE TRANSPORTS — `liveClock` and `offlineTransport`. Upstream of everything: if the
 *      pair is absent here, every surface below silently falls back to the timeline clock
 *      and the property fails everywhere at once. `offlineTransport` published no pair at
 *      all until T489, so a rendered or headless lap wrapped abstime along with time.
 *   2. THE EXPRESSION SCOPE — `scopeFromFrame` (`abstime`, `absframe`), T461.
 *   3. THE FRAMELESS SCOPE — `resolveParameters` with no frame (a Text node's raster, a
 *      component instance's published values). Its zero scope was a hand-written list four
 *      names behind `scopeFromFrame`, so `abstime * 90` FAILED there while `time * 90`
 *      resolved to 0. Fixed by derivation (T489).
 *   4. THE SHARED FRAME BLOCK — `SharedFrame.absTime`/`absFrame`, what every texture shader
 *      and custom-WGSL node reads, T468.
 *   5. POINT KERNELS — `ctx.absTime`/`ctx.absFrame` on `PointCtx`, use-detected, B97/T489.
 *   6. GROUP PREDICATES — compiled against the same `PointCtx`, so the kernel's detection
 *      must scan the predicate text too.
 *   7. SPAWN HOOKS — their own `PointCtx`, generated by a separate function that has to be
 *      taught separately. This is exactly the "site five" this file exists to catch.
 *   8. DISPATCH UNIFORMS — `dispatchFrameUniforms`, the per-frame write into a kernel's own
 *      block. A kernel can declare `absTimeSeconds` and still read zero forever if nothing
 *      fills it, and that failure is silent because vgpu matches by name.
 *   9. VALUE NODES — every `valueChannel`/`valueEvaluate` node. Here the property is not
 *      "always absolute": §V436 says a node's clock is a DESIGN DECISION, so the gate is
 *      that every node is CLASSIFIED and the free-running ones survive a lap.
 *
 * ## What is deliberately NOT asserted
 *
 * That `time` and `frame` keep growing — they must NOT. A timeline that wraps is the
 * feature (T455/T464); the absolute clock is what you reach for when you need continuity.
 * Asserting monotonicity of the timeline pair would be asserting the bug.
 *
 * ## Determinism is untouched (§V44/§V47)
 *
 * Everything here is a frame COUNT at the timeline rate. Nothing reads a wall clock, and a
 * render zeroes the absolute clock first (T467), so a take reproduces. The last describe
 * block asserts that rather than trusting it.
 */

/** How many frames each side of the lap the property is sampled over. */
const LAP_AT = 8;
const AFTER_LAP = 6;

/**
 * One clock-reading surface: a name and the numbers it exposes for a given frame.
 *
 * Every entry returns the ABSOLUTE readings only. A surface that also exposes the timeline
 * clock exposes it deliberately, and the timeline clock is supposed to wrap.
 */
interface ClockSurface {
  readonly name: string;
  read(frame: FrameEvaluationInput): Readonly<Record<string, number>>;
}

const POINTER = { x: 0, y: 0, buttons: 0 };
const RESOLUTION: readonly [number, number] = [16, 16];

const sharedFor = (frame: FrameEvaluationInput) =>
  sharedUniformsFromFrame({ frame, pointer: POINTER, resolution: RESOLUTION });

/** A parameter node whose expression reads `abstime` — surface 3's probe. */
const ABSTIME_NODE: GraphNode = {
  id: "n1",
  type: "probe",
  definitionVersion: 1,
  position: { x: 0, y: 0 },
  parameters: {
    amount: { mode: "expression", bindings: { expression: { kind: "expression", source: "abstime" } } },
  },
};

const ABSTIME_DEFINITION = {
  type: "probe",
  version: 1,
  title: "Probe",
  category: "value",
  description: "",
  inputs: [],
  outputs: [],
  parameters: { amount: { type: "number" as const, label: "Amount", default: -1 } },
  compile: () => ({ passes: [] }),
} as unknown as NodeDefinition;

const KERNEL_ATTRIBUTES: readonly PointAttributeSchema[] = [
  { name: "position", type: "vec3f", semantic: "position", default: [0, 0, 0] },
];

/** A kernel that reads the absolute pair, so the generated block must carry it. */
const ABS_KERNEL = `fn process(p: Point, ctx: PointCtx) -> Point {
  var q = p;
  q.position.x = ctx.absTime + f32(ctx.absFrame);
  return q;
}`;

const ABS_HOOK = `fn spawn(child: Point, ctx: PointCtx) -> Point {
  var q = child;
  q.position.y = ctx.absTime;
  return q;
}`;

function kernelModule(kernel: string, group = ""): { wgsl: string; usesAbsClock: boolean } {
  const module = generateKernelModule({
    attributes: [...KERNEL_ATTRIBUTES],
    reads: ["position"],
    writes: ["position"],
    kernel,
    ...(group === "" ? {} : { group }),
  });
  if (!module.ok) throw new Error(`kernel did not compile: ${module.errors.join("; ")}`);
  return { wgsl: module.wgsl, usesAbsClock: module.usesAbsClock };
}

function hookModule(hook: string): { wgsl: string; usesAbsClock: boolean } {
  const module = generateSpawnHookModule({
    attributes: [...KERNEL_ATTRIBUTES, { name: "flags", type: "u32" as const, default: [0] }],
    flagsAttribute: "flags",
    hook,
  });
  if (!module.ok) throw new Error(`hook did not compile: ${module.errors.join("; ")}`);
  return { wgsl: module.wgsl, usesAbsClock: module.usesAbsClock };
}

/**
 * THE ENUMERATION. Adding a surface here is how site N+1 gets covered; the two structural
 * tests further down are what make forgetting to add one fail rather than ship.
 */
const SURFACES: readonly ClockSurface[] = [
  {
    name: "expression scope (T461)",
    read: (frame) => {
      const scope = scopeFromFrame(frame);
      const evaluated = evaluateExpression("abstime * 90", scope);
      if (!evaluated.ok) throw new Error(`expression scope rejected abstime: ${evaluated.reason}`);
      return {
        abstime: scope["abstime"] as number,
        absframe: scope["absframe"] as number,
        // The name being IN the scope and the evaluator ACCEPTING it are two different
        // reachabilities, and surface 3 was broken on exactly that difference.
        "abstime * 90": evaluated.value,
      };
    },
  },
  {
    name: "shared frame block — texture shaders and custom WGSL (T468)",
    read: (frame) => {
      const shared = sharedFor(frame);
      return { absTime: shared.absTime, absFrame: shared.absFrame };
    },
  },
  {
    name: "dispatch uniforms — what a point kernel's own block is filled with (T489)",
    read: (frame) => {
      const written = dispatchFrameUniforms(frame, sharedFor(frame));
      return {
        absTimeSeconds: written["absTimeSeconds"] as number,
        absFrameIndex: written["absFrameIndex"] as number,
      };
    },
  },
  {
    name: "value nodes — the FREE-RUNNING ones (§V436, B98)",
    read: (frame) => {
      const readings: Record<string, number> = {};
      for (const definition of freeRunningValueNodes()) {
        // A free-running source's own output oscillates; what must not go backwards is the
        // CLOCK it is a function of. Reading that clock through the same helper the node
        // reads it through is the assertion that matters — the node's own number is
        // asserted separately, in the LFO's own describe block below.
        readings[`${definition.type}.clock`] = absTimeSecondsOf(frame);
      }
      return readings;
    },
  },
  {
    name: "frameless parameter resolve — Text raster, component instance values (T489)",
    read: () => {
      const resolved = resolveParameters(ABSTIME_NODE, ABSTIME_DEFINITION);
      const value = resolved.values["amount"];
      if (typeof value !== "number") throw new Error("frameless resolve did not produce a number");
      // Constant by construction (there IS no frame here), and constant is non-decreasing.
      // What this surface can actually fail is REJECTING the name, which shows up as the
      // manifest default (-1) instead of 0 — see the dedicated test below.
      return { "abstime (no frame)": value };
    },
  },
];

/** Value nodes whose description declares them free-running on the absolute clock. */
function freeRunningValueNodes(): readonly NodeDefinition[] {
  return allNodeDefinitions.filter((definition) => CLOCK_OWNERSHIP[definition.type] === "free-running");
}

/**
 * §V436 — WHICH CLOCK EACH VALUE NODE OWNS, and it is a decision, never a default.
 *
 * Derived-against rather than hand-checked: the test below asks the REGISTRY for every node
 * declaring `valueChannel` or `valueEvaluate` and fails if one is missing from this map. So
 * value node #14 cannot land without its author deciding which clock it reads — which is
 * the whole of B98, whose LFO was put on the timeline clock by nobody deciding anything.
 */
const CLOCK_OWNERSHIP: Readonly<Record<string, "free-running" | "timeline-anchored" | "delta-driven" | "clockless">> = {
  // FREE-RUNNING: "always going" is the idea of the node, so a timeline lap must not touch
  // it. TD's LFO CHOP is free-running, which is why it laps seamlessly at any frequency.
  lfo: "free-running",
  // TIMELINE-ANCHORED: where you are IN the piece is the point, so it wraps BY DESIGN.
  // Turning either of these free-running would be a different bug, not the same fix.
  timer: "timeline-anchored",
  audioPattern: "timeline-anchored",
  // DELTA-DRIVEN: reads the frame STEP, never a clock position. A lap carries a real step
  // (T464), so these pass through a loop boundary with no discontinuity at all.
  valueSlope: "delta-driven",
  valueLag: "delta-driven",
  valueFilter: "delta-driven",
  // CLOCKLESS: reads no clock. A loop cannot reach them.
  constant: "clockless",
  mouse: "clockless",
  valueMath: "clockless",
  valueLimit: "clockless",
  valueTrigger: "clockless",
  // T508: a Switch selects. It has no phase and no state, so a lap cannot reach it —
  // whatever the SELECTED input does across a loop boundary, the Switch does.
  valueSwitch: "clockless",
  // T548: a Step quantises a COUNT that arrives on its input and hashes it. It reads no
  // clock at all, which is deliberate rather than incidental: it INHERITS its source's
  // clock, so bar-locked steps stay bar-locked when the source is swapped for one on a
  // different clock. An LFO in `noise` mode is the same sample-and-hold on a clock of its
  // OWN, and that is exactly why it could not be used for bars (B98 made it free-running).
  valueStep: "clockless",
  audioIn: "clockless",
  audioFileIn: "clockless",
};

function valueNodes(): readonly NodeDefinition[] {
  return allNodeDefinitions.filter(
    (definition) => definition.valueChannel !== undefined || definition.valueEvaluate !== undefined,
  );
}

/**
 * §V453 EXTENDED TO A SECOND CATEGORY (T493), and structured as a CLAUSE PER KIND rather
 * than a special case — which is §V316's own rule, stated over exactly this failure: an
 * invariant written for one member silently narrows when member #2 appears.
 *
 * A MEDIA TRANSPORT is a clock owner that is not a value node. `movieFileIn` publishes no
 * channel at all, so `valueNodes()` never saw it, and it could have shipped a playhead on
 * any clock it liked without this file noticing. Its position is now the single most
 * clock-sensitive thing in the catalogue: put it on a free-running clock and a scrub finds
 * a different frame every time and an offline render stops reproducing (§V45/§V47).
 *
 * Note `audioFileIn` is in BOTH tables, with DIFFERENT answers, and that is the point
 * rather than a wart: its CHANNELS are clockless (what the analyser heard this frame) and
 * its PLAYHEAD is timeline-anchored (where the track is in the piece). One entry per node
 * would have forced one of those two true statements to be dropped.
 *
 * T586 — WHAT THIS TABLE CLASSIFIES IS NOT THE DEFAULT. The owner moved the `playMode`
 * DEFAULT to free run; a media node therefore ARRIVES free-running. The classification is
 * unchanged and deliberately so: it names the clock the playhead is DEFINED AGAINST — the
 * anchor the node offers, the mode in which its position means "where the track is in the
 * piece" and a scrub and an offline render reproduce. What §V453 gates is that an author
 * DECIDED, not which mode a fresh node lands in, and both nodes still declare and document
 * both clocks. The gap the flip opens — a project that arrives on the mode that does NOT
 * reproduce — is closed at render time by `freeRunMediaNodes` naming the offenders, not by
 * softening what the node says it is.
 *
 * Derived from `hasMediaTransport`, which asks the node's own parameter schema — so media
 * node N+1 fails here until its author decides, with nothing to remember to update.
 */
const TRANSPORT_CLOCK_OWNERSHIP: Readonly<
  Record<string, "free-running" | "timeline-anchored" | "delta-driven" | "clockless">
> = {
  movieFileIn: "timeline-anchored",
  audioFileIn: "timeline-anchored",
};

function mediaTransportNodes(): readonly NodeDefinition[] {
  return allNodeDefinitions.filter((definition) => hasMediaTransport(definition));
}

/** Frames either side of a lap, from a real transport rather than hand-built objects. */
function framesAcrossLap(transport: ReturnType<typeof liveClock>): {
  before: readonly FrameEvaluationInput[];
  after: readonly FrameEvaluationInput[];
} {
  const before: FrameEvaluationInput[] = [];
  for (let index = 0; index < LAP_AT; index += 1) before.push(transport.next());
  transport.wrapTo?.(0);
  const after: FrameEvaluationInput[] = [];
  for (let index = 0; index < AFTER_LAP; index += 1) after.push(transport.next());
  return { before, after };
}

describe("T489 — no clock-reading surface sees a value decrease across a loop boundary", () => {
  const transports = [
    ["liveClock", () => liveClock({ fps: 60, now: () => 0 })],
    ["offlineTransport", () => offlineTransport({ fps: 60 })],
  ] as const;

  for (const [transportName, make] of transports) {
    for (const surface of SURFACES) {
      it(`${surface.name} — monotone across a lap on ${transportName}`, () => {
        const { before, after } = framesAcrossLap(make() as ReturnType<typeof liveClock>);
        const frames = [...before, ...after];

        // The lap really happened: the TIMELINE clock went backwards. Without this the
        // whole file could pass against a transport that never wrapped, which is the
        // vacuous-green shape a property test is easiest to get wrong in.
        const lastBefore = before[before.length - 1];
        const firstAfter = after[0];
        expect(lastBefore).toBeDefined();
        expect(firstAfter).toBeDefined();
        expect(firstAfter?.frameIndex ?? -1).toBeLessThan(lastBefore?.frameIndex ?? -1);

        const readings = frames.map((frame) => surface.read(frame));
        const keys = Object.keys(readings[0] ?? {});
        expect(keys.length).toBeGreaterThan(0);

        for (const key of keys) {
          for (let index = 1; index < readings.length; index += 1) {
            const previous = readings[index - 1]?.[key];
            const current = readings[index]?.[key];
            expect(
              current,
              `${surface.name}: "${key}" went BACKWARDS at frame ${index} (${String(previous)} → ${String(current)}) — ` +
                "something the timeline lap reset. See T489/§V437.",
            ).toBeGreaterThanOrEqual(previous as number);
          }
        }
      });
    }
  }

  it("the absolute clock actually ADVANCES across the lap — not merely non-decreasing", () => {
    // Monotone is satisfiable by a constant, and a constant abstime is its own bug. This
    // is the half that says the clock is running, on the transport that had none.
    for (const [, make] of transports) {
      const { before, after } = framesAcrossLap(make() as ReturnType<typeof liveClock>);
      const first = before[0];
      const last = after[after.length - 1];
      expect(absFrameIndexOf(last as FrameEvaluationInput)).toBeGreaterThan(
        absFrameIndexOf(first as FrameEvaluationInput),
      );
      expect(absTimeSecondsOf(last as FrameEvaluationInput)).toBeGreaterThan(
        absTimeSecondsOf(first as FrameEvaluationInput),
      );
    }
  });

  it("the TIMELINE clock still wraps — the property is about abstime, not about killing the loop", () => {
    const { before, after } = framesAcrossLap(liveClock({ fps: 60, now: () => 0 }));
    expect(after[0]?.timeSeconds).toBe(0);
    expect(before[before.length - 1]?.timeSeconds).toBeGreaterThan(0);
  });
});

/**
 * The structural half. The tests above are only as good as `SURFACES`, so these are the
 * ones that fail when a NEW surface appears without being added to it.
 */
describe("T489 — a surface cannot be added without declaring its clock", () => {
  it("every value node in the registry is classified against §V436", () => {
    const unclassified = valueNodes()
      .map((definition) => definition.type)
      .filter((type) => CLOCK_OWNERSHIP[type] === undefined);
    expect(
      unclassified,
      "a value node landed without deciding which clock it reads (§V436). Add it to " +
        "CLOCK_OWNERSHIP and say why in its description — B98 is what defaulting costs.",
    ).toEqual([]);
  });

  it("CLOCK_OWNERSHIP names no node that has stopped existing", () => {
    const live = new Set(valueNodes().map((definition) => definition.type));
    const stale = Object.keys(CLOCK_OWNERSHIP).filter((type) => !live.has(type));
    expect(stale, "the classification has rotted past the catalogue (§V421)").toEqual([]);
  });

  it("every node classified free-running states so in its description, where the user reads it", () => {
    for (const definition of freeRunningValueNodes()) {
      expect((definition.description ?? "").toLowerCase(), `${definition.type}`).toContain("free-running");
    }
  });

  it("every node classified timeline-anchored says so too, so the contrast is visible", () => {
    for (const definition of allNodeDefinitions) {
      if (CLOCK_OWNERSHIP[definition.type] !== "timeline-anchored") continue;
      expect((definition.description ?? "").toLowerCase(), `${definition.type}`).toContain("timeline-anchored");
    }
  });

  /* T493 — the same three assertions over the media-transport category (§V453, §V316). */

  it("every media-transport node in the registry is classified against §V436", () => {
    const unclassified = mediaTransportNodes()
      .map((definition) => definition.type)
      .filter((type) => TRANSPORT_CLOCK_OWNERSHIP[type] === undefined);
    expect(
      unclassified,
      "a node grew a media transport without deciding which clock its PLAYHEAD reads " +
        "(§V436). Add it to TRANSPORT_CLOCK_OWNERSHIP and say why in its description — a " +
        "free-running playhead cannot be scrubbed and cannot be rendered offline.",
    ).toEqual([]);
  });

  it("TRANSPORT_CLOCK_OWNERSHIP names no node that has stopped carrying a transport", () => {
    const live = new Set(mediaTransportNodes().map((definition) => definition.type));
    const stale = Object.keys(TRANSPORT_CLOCK_OWNERSHIP).filter((type) => !live.has(type));
    expect(stale, "the classification has rotted past the catalogue (§V421)").toEqual([]);
  });

  it("both media doors carry the SAME transport, so learning one teaches the other", () => {
    // The anti-drift assertion: T493's whole shape is one vocabulary behind two nodes, and
    // the way that decays is one door quietly gaining a key the other never gets.
    const types = mediaTransportNodes().map((definition) => definition.type);
    expect(types).toContain("movieFileIn");
    expect(types).toContain("audioFileIn");
    for (const definition of mediaTransportNodes()) {
      for (const key of MEDIA_TRANSPORT_KEYS) {
        expect(definition.parameters?.[key], `${definition.type}.${key}`).toBe(
          MEDIA_TRANSPORT_PARAMETERS[key],
        );
      }
    }
  });

  it("every media-transport node classified timeline-anchored states it where the user reads it", () => {
    for (const definition of mediaTransportNodes()) {
      if (TRANSPORT_CLOCK_OWNERSHIP[definition.type] !== "timeline-anchored") continue;
      expect((definition.description ?? "").toLowerCase(), `${definition.type}`).toContain(
        "timeline-anchored",
      );
    }
  });

  /**
   * T586 — and the node must ALSO say which mode it ARRIVES on, which the assertion above
   * cannot see.
   *
   * §V453's rule is that the classification lives in the text the user reads, not only in
   * the gate's table. The flip splits that in two: the node is timeline-anchored WHEN
   * LOCKED, and free-running WHEN FRESH, and a description naming only the first is the
   * shape §V338 objects to — true, and quietly missing the half that describes what will
   * actually happen. So both halves are asserted, and a silent revert of the default in
   * either direction now reddens the docs rather than only the arithmetic.
   */
  it("every media-transport node also states the mode it ARRIVES on, which is now free run", () => {
    for (const definition of mediaTransportNodes()) {
      const text = (definition.description ?? "").toLowerCase();
      expect(text, `${definition.type} must name its default mode`).toContain("free run");
      expect(text, `${definition.type} must say free run is the DEFAULT`).toContain("by default");
      expect(
        definition.parameters?.["playMode"],
        `${definition.type}: the description and the manifest must agree about the default`,
      ).toMatchObject({ default: "freeRun" });
    }
  });
});

/**
 * T493 — THE MEDIA PLAYHEAD ACROSS A LAP, on real transports.
 *
 * A timeline-anchored playhead is SUPPOSED to wrap: that is what anchoring means, and
 * asserting monotonicity here would be asserting the opposite bug (see "What is
 * deliberately NOT asserted" above). What the lap must not do is make the position depend
 * on HOW you got there — so the assertion is REPRODUCIBILITY: the frame after the lap sees
 * exactly the position the same timeline frame saw the first time round, while the
 * absolute clock underneath keeps counting (§V449).
 */
describe("T493 — the media playhead wraps with the timeline and reproduces exactly", () => {
  const LOOPING: MediaTransportValues = {
    playMode: "timeline",
    play: true,
    speed: 1,
    cue: false,
    cuePoint: 0,
    trimStart: 0,
    trimEnd: 0,
    extend: "loop",
  };

  for (const [transportName, make] of [
    ["liveClock", () => liveClock({ fps: 60, now: () => 0 })],
    ["offlineTransport", () => offlineTransport({ fps: 60 })],
  ] as const) {
    it(`a lap replays the same positions on ${transportName}, and abstime does not rewind`, () => {
      const { before, after } = framesAcrossLap(make() as ReturnType<typeof liveClock>);
      // The window is 4s and the lap is at frame 8 of a 60fps clock, so the wrap happens
      // nowhere near a window boundary — the case a "just make it divide" answer cannot
      // handle (§V435's mistake, restated for media).
      const positionAt = (frame: FrameEvaluationInput) =>
        mediaPlayhead(LOOPING, frame.timeSeconds, 4).position;

      // Guard against the vacuous version: the lap really happened.
      expect(after[0]?.frameIndex).toBeLessThan(before[before.length - 1]?.frameIndex ?? -1);

      for (let index = 0; index < after.length; index += 1) {
        const replayed = after[index] as FrameEvaluationInput;
        const original = before[index] as FrameEvaluationInput;
        expect(replayed.frameIndex).toBe(original.frameIndex);
        // EXACT, not close: the position is arithmetic on the frame, with no accumulator
        // anywhere for a rounding difference to creep into.
        expect(positionAt(replayed)).toBe(positionAt(original));
        // ...and the thing §V449 protects kept going while the media rewound.
        expect(absFrameIndexOf(replayed)).toBeGreaterThan(absFrameIndexOf(original));
      }
    });
  }

  it("a FREE-RUN playhead does NOT come back — which is the determinism it costs you", () => {
    // The counter-example that proves the default is doing work. Same lap, same window;
    // the free-run clock accumulates across it, so the position after the lap is somewhere
    // the first pass never was.
    const freeRun: MediaTransportValues = { ...LOOPING, playMode: "freeRun" };
    const clock = createMediaClock();
    const { before, after } = framesAcrossLap(liveClock({ fps: 60, now: () => 0 }));
    const positions: number[] = [];
    for (const frame of [...before, ...after]) {
      positions.push(
        mediaPlayhead(freeRun, clock.advance(freeRun, frame.deltaSeconds, frame.timeSeconds), 4)
          .position,
      );
    }
    const firstPass = positions.slice(0, before.length);
    const afterLap = positions.slice(before.length);
    for (let index = 0; index < afterLap.length; index += 1) {
      expect(afterLap[index], `free-run position at lap frame ${index}`).not.toBe(firstPass[index]);
    }
    // And it is strictly ahead, not merely different.
    expect(afterLap[0]).toBeGreaterThan(firstPass[firstPass.length - 1] as number);
  });
});

/**
 * B98 — the LFO, and it is stated as the OWNER'S complaint rather than as an implementation
 * detail: "at 0.3 Hz it jumps at the loop". §V435 answered that with arithmetic (choose a
 * frequency that divides the loop) and the arithmetic was true and the answer was wrong —
 * it explained a defect as a constraint the author must work around.
 */
describe("B98 — the LFO is free-running, so it laps seamlessly at ANY frequency", () => {
  const lfo = () => {
    const definition = allNodeDefinitions.find((entry) => entry.type === "lfo");
    if (definition?.valueChannel === undefined) throw new Error("no lfo node with a valueChannel");
    return definition.valueChannel.bind(definition);
  };

  it("does not snap back at the lap, at a frequency that does NOT divide the loop", () => {
    const evaluate = lfo();
    // 0.3 Hz against a 12-frame loop at 60fps: the phase at the wrap is nowhere near a
    // cycle boundary, which is precisely the case the old answer had no answer for.
    const values = { shape: "sine", frequency: 0.3, amplitude: 1, offset: 0, phase: 0 };
    const clock = liveClock({ fps: 60, now: () => 0 });
    const samples: number[] = [];
    for (let index = 0; index < 12; index += 1) samples.push(evaluate(values, clock.next()));
    clock.wrapTo?.(0);
    const atWrap = evaluate(values, clock.next());

    const lastBefore = samples[samples.length - 1] as number;
    const stepBefore = Math.abs(lastBefore - (samples[samples.length - 2] as number));
    // The step ACROSS the wrap must look like every other step. On the timeline clock this
    // was a jump back to the phase of frame zero — an order of magnitude larger.
    expect(Math.abs(atWrap - lastBefore)).toBeLessThan(stepBefore * 3 + 1e-9);
  });

  it("keeps a rising sine rising through the lap rather than restarting its cycle", () => {
    const evaluate = lfo();
    const values = { shape: "saw", frequency: 0.25, amplitude: 1, offset: 0, phase: 0 };
    const clock = liveClock({ fps: 60, now: () => 0 });
    let last = Number.NEGATIVE_INFINITY;
    for (let index = 0; index < 10; index += 1) last = evaluate(values, clock.next());
    clock.wrapTo?.(0);
    // A saw at 0.25 Hz has a four-second period; ten frames in, it is a fifth of the way up
    // and still climbing. Restarting the timeline must not put it back at the bottom.
    expect(evaluate(values, clock.next())).toBeGreaterThan(last);
  });

  it("the TIMER, next door, still wraps — §V436 is a distinction, not a blanket swap", () => {
    const definition = allNodeDefinitions.find((entry) => entry.type === "timer");
    if (definition?.valueChannel === undefined) throw new Error("no timer node with a valueChannel");
    const values = { speed: 1, delay: 0 };
    const clock = liveClock({ fps: 60, now: () => 0 });
    let last = 0;
    for (let index = 0; index < 10; index += 1) last = definition.valueChannel(values, clock.next());
    clock.wrapTo?.(0);
    // Timeline-anchored BY DESIGN: a Timer that kept climbing across the lap would no
    // longer answer "where am I in the piece", which is the only question it exists for.
    expect(definition.valueChannel(values, clock.next())).toBeLessThan(last);
  });
});

/**
 * B97 — `ctx.absTime` / `ctx.absFrame` on `PointCtx`, the fourth member of the family
 * `ctx.pointer` / `ctx.dim` / `ctx.value1..4` established (§V309).
 */
describe("B97 — point kernels can read the clock that does not reset", () => {
  it("a kernel naming ctx.absTime gets both members, wired from the frame block", () => {
    const { wgsl, usesAbsClock } = kernelModule(ABS_KERNEL);
    expect(usesAbsClock).toBe(true);
    expect(wgsl).toContain("absTimeSeconds: f32,");
    expect(wgsl).toContain("absFrameIndex: u32,");
    expect(wgsl).toContain("absTime: f32,");
    expect(wgsl).toContain("absFrame: u32,");
    // Declared is not enough: the ctx CONSTRUCTOR has to pass them, or the member reads
    // whatever the previous argument left in it.
    expect(wgsl).toContain("kernelFrame.absTimeSeconds, kernelFrame.absFrameIndex");
  });

  it("§V309 — a kernel that never mentions it emits BYTE-IDENTICAL WGSL", () => {
    const plain = `fn process(p: Point, ctx: PointCtx) -> Point {
  var q = p;
  q.position.x = ctx.time;
  return q;
}`;
    const { wgsl, usesAbsClock } = kernelModule(plain);
    expect(usesAbsClock).toBe(false);
    expect(wgsl).not.toContain("abs");
    // The property this family lives or dies by, stated as the text rather than as a
    // feeling: every point graph ever saved compiles to exactly what it compiled to.
    expect(wgsl).toBe(kernelModule(plain).wgsl);
  });

  it("a GROUP PREDICATE reading ctx.absTime declares the member too — same ctx, T300", () => {
    const plain = `fn process(p: Point, ctx: PointCtx) -> Point { return p; }`;
    const { wgsl, usesAbsClock } = kernelModule(plain, "ctx.absTime > 1.0");
    expect(usesAbsClock).toBe(true);
    expect(wgsl).toContain("absTime: f32,");
    // Dawn would otherwise refuse with "struct PointCtx has no member named 'absTime'",
    // which is loud but is a compile failure the author cannot fix (§V288).
    expect(wgsl).toContain("groupMatch");
  });

  it("a SPAWN HOOK reading ctx.absTime declares it — the separate generator, site five", () => {
    const { wgsl, usesAbsClock } = hookModule(ABS_HOOK);
    expect(usesAbsClock).toBe(true);
    expect(wgsl).toContain("absTimeSeconds: f32,");
    expect(wgsl).toContain("absTime: f32,");
    expect(wgsl).toContain("kernelFrame.absTimeSeconds, kernelFrame.absFrameIndex");
  });

  it("§V309 — a spawn hook that never mentions it is byte-identical too", () => {
    const plain = `fn spawn(child: Point, ctx: PointCtx) -> Point { return child; }`;
    const { wgsl, usesAbsClock } = hookModule(plain);
    expect(usesAbsClock).toBe(false);
    expect(wgsl).not.toContain("abs");
  });

  it("the per-frame write names EXACTLY the members the generated block declares", () => {
    // The silent half of this feature: vgpu matches uniforms by NAME, so a declared member
    // nothing writes reads zero forever and looks like a stopped clock, while a written
    // name nothing declares is dropped without a word. Both halves, one assertion.
    const { wgsl } = kernelModule(ABS_KERNEL);
    const written = dispatchFrameUniforms(
      { timeSeconds: 1, deltaSeconds: 1 / 60, frameIndex: 60, mode: "offline", randomSeed: 7 },
      sharedFor({ timeSeconds: 1, deltaSeconds: 1 / 60, frameIndex: 60, mode: "offline", randomSeed: 7 }),
    );
    for (const name of ["absTimeSeconds", "absFrameIndex"]) {
      expect(wgsl, `${name} is declared by codegen`).toContain(`${name}:`);
      expect(Object.keys(written), `${name} is written every frame`).toContain(name);
    }
  });
});

/**
 * T489, surface 3. `evaluateExpression` treats an unknown name as a HARD failure, so a
 * scope missing `abstime` does not degrade to zero — it refuses, and the parameter falls
 * back to its manifest default. Silent everywhere the diagnostic is not surfaced.
 */
describe("T489 — the frameless resolve scope offers the same names as a real frame", () => {
  it("resolves `abstime` to the deterministic zero rather than refusing it", () => {
    const resolved = resolveParameters(ABSTIME_NODE, ABSTIME_DEFINITION);
    // 0, not the manifest default of -1: the name is KNOWN here, it simply has no frame.
    expect(resolved.values["amount"]).toBe(0);
  });

  it("offers every name `scopeFromFrame` does, by derivation rather than by a second list", () => {
    const real = Object.keys(
      scopeFromFrame({ timeSeconds: 0, deltaSeconds: 0, frameIndex: 0, mode: "offline", randomSeed: 0 }),
    ).sort();
    for (const name of real) {
      const node: GraphNode = {
        ...ABSTIME_NODE,
        parameters: {
          amount: { mode: "expression", bindings: { expression: { kind: "expression", source: name } } },
        },
      };
      expect(resolveParameters(node, ABSTIME_DEFINITION).values["amount"], `frameless scope knows "${name}"`).toBe(0);
    }
  });
});

/**
 * T467/§V44 — the guard rail on the whole feature. The absolute clock is what makes a loop
 * survivable; a WALL clock would do that too and would quietly destroy reproducibility,
 * looking perfectly correct in every live session while doing it.
 */
describe("T489 — the absolute clock stays deterministic", () => {
  it("is a frame count at the timeline rate, unmoved by how long the wall clock took", () => {
    let ms = 0;
    const fast = liveClock({ fps: 60, now: () => (ms += 500) });
    const slow = liveClock({ fps: 60, now: () => (ms += 1) });
    for (let index = 0; index < 20; index += 1) {
      fast.next();
      slow.next();
    }
    const a = fast.next();
    const b = slow.next();
    expect(a.absTimeSeconds).toBeCloseTo(b.absTimeSeconds ?? -1, 10);
    expect(a.absFrameIndex).toBe(b.absFrameIndex);
  });

  it("a RENDER zeroes it, so the same project renders the same bytes on two different days", () => {
    const day = (age: number) => {
      const clock = offlineTransport({ fps: 60 });
      for (let index = 0; index < age; index += 1) clock.next();
      clock.resetAbsolute();
      return [clock.next(), clock.next(), clock.next()].map((frame) => absTimeSecondsOf(frame));
    };
    expect(day(0)).toEqual(day(37));
  });

  it("the shared block and the expression scope carry the SAME number (§V182)", () => {
    const clock = liveClock({ fps: 60, now: () => 0 });
    for (let index = 0; index < 5; index += 1) clock.next();
    clock.wrapTo?.(0);
    const frame = clock.next();
    expect(sharedFor(frame).absTime).toBe(scopeFromFrame(frame)["abstime"]);
    expect(sharedFor(frame).absFrame).toBe(scopeFromFrame(frame)["absframe"]);
  });

  it("SHARED_UNIFORMS_WGSL declares the pair the writer fills", () => {
    expect(SHARED_UNIFORMS_WGSL).toContain("absTime: f32,");
    expect(SHARED_UNIFORMS_WGSL).toContain("absFrame: f32,");
  });
});
